version: "3"
services:
# this container will run Cypress test using Chrome browser
  e2e-chrome:
    image: "cytest-dockerimage10"
    command: "chrome:test"
    volumes:
      - ./cypress/videos:/cypress-docker/cypress/videos
      - ./cypress/reports:/cypress-docker/cypress/reports
  # this container will run Cypress test using built-in Electron browser
  e2e-electron:
    image: "cytest-dockerimage10"
    command: "test"
    volumes:
      - ./cypress/videos:/cypress-docker/cypress/videos
      - ./cypress/reports:/cypress-docker/cypress/reports
